import { z } from 'zod';

/**
 * Account interface representing a bank account
 *
 * Note: Balance is stored in cents to avoid floating point precision issues
 * Pin is stored as a hashed value for security (never plain text)
 */
export interface Account {
	accountNumber: string; // 10-digit account number
	pin: string; // Hashed PIN (bcrypt hash)
	balance: number; // Balance in cents (allow negative for overdrafts)
	createdAt: Date; // Creation timestamp
	updatedAt: Date; // Last modification timestamp
}

/**
 * Zod schema for Account validation
 * Ensures data integrity and type safety
 */
export const AccountSchema = z.object({
	accountNumber: z
		.string()
		.length(10, 'Account number must be exactly 10 digits')
		.regex(/^\d{10}$/, 'Account number must contain only digits'),
	pin: z.string().min(1, 'PIN hash is required'),
	balance: z.number().int('Balance must be an integer (cents)'),
	createdAt: z.date(),
	updatedAt: z.date(),
});

/**
 * Schema for creating a new account (without timestamps)
 * Timestamps are auto-generated by the storage layer
 */
export const CreateAccountSchema = AccountSchema.omit({
	createdAt: true,
	updatedAt: true,
});

/**
 * Schema for updating an account
 * All fields are optional for partial updates
 */
export const UpdateAccountSchema = AccountSchema.partial();

/**
 * Type for creating a new account
 */
export type CreateAccount = z.infer<typeof CreateAccountSchema>;

/**
 * Type for updating an account
 */
export type UpdateAccount = z.infer<typeof UpdateAccountSchema>;
