import { z } from 'zod';

/**
 * Transaction type enum
 */
export enum TransactionType {
  DEPOSIT = 'deposit',
  WITHDRAWAL = 'withdrawal',
  TRANSFER = 'transfer',
}

/**
 * Transaction status enum
 */
export enum TransactionStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

/**
 * Transaction interface representing a banking transaction
 * 
 * Provides audit trail with balance snapshots before and after
 */
export interface Transaction {
  id: string;                // Unique transaction ID (UUID)
  accountNumber: string;     // Associated account
  type: TransactionType;     // Transaction type
  amount: number;            // Amount in cents (positive for all types)
  balanceBefore: number;     // Balance before transaction (in cents)
  balanceAfter: number;      // Balance after transaction (in cents)
  timestamp: Date;           // Transaction timestamp
  status: TransactionStatus; // Transaction status
  description?: string;      // Optional description
}

/**
 * Zod schema for Transaction validation
 */
export const TransactionSchema = z.object({
  id: z.string().uuid('Transaction ID must be a valid UUID'),
  accountNumber: z
    .string()
    .length(10, 'Account number must be exactly 10 digits')
    .regex(/^\d{10}$/, 'Account number must contain only digits'),
  type: z.nativeEnum(TransactionType),
  amount: z
    .number()
    .int('Amount must be an integer (cents)')
    .positive('Amount must be positive'),
  balanceBefore: z
    .number()
    .int('Balance before must be an integer (cents)'),
  balanceAfter: z
    .number()
    .int('Balance after must be an integer (cents)'),
  timestamp: z.date(),
  status: z.nativeEnum(TransactionStatus),
  description: z.string().optional(),
});

/**
 * Schema for creating a new transaction (without ID and timestamp)
 * ID and timestamp are auto-generated by the storage layer
 */
export const CreateTransactionSchema = TransactionSchema.omit({
  id: true,
  timestamp: true,
});

/**
 * Type for creating a new transaction
 */
export type CreateTransaction = z.infer<typeof CreateTransactionSchema>;
